export const productHeaderMappings = {
    en: {
      "QR Code": "qrcode",
      "Category": "category",
      "Weight": "weightDetail.weight",
      "Is Sold By Weight": "weightDetail.isSoldByWeight",
      "Weight Unit": "weightDetail.weightUnit",
      "Net Content": "netContent",
      "Size": "size",
      "Name": "name",
      "Measurement": "measurement",
      "Promotion End": "promotions.end",
      "Promotion Active": "promotions.isActive",
      "Discount": "promotions.discount",
      "Promotion Start": "promotions.start",
      "Image": "image",
      "Is Visible": "isVisible",
      "Order": "order",
      "Footer": "footer",
      "Type": "type",
      "Tax": "pricing.tax",
      "List Price": "pricing.listPrice",
      "Average Price": "pricing.avgPrice",
      "Price": "pricing.price",
      "Cost": "pricing.cost",
      "Minimum Price": "pricing.minPrice",
      "Status": "status",
      "Stock": "stock",
      "Warranty Status": "warranty.status",
      "Warranty Quantity": "warranty.quantity",
      "Warranty Unit": "warranty.unit",
      "Amount to Buy": "amountToBuy",
      "Track Inventory": "trackInventory",
      "Barcode": "barcode"
    },
    es: {
      "Código QR": "qrcode",
      "Categoría": "category",
      "Peso": "weightDetail.weight",
      "Se Vende por Peso": "weightDetail.isSoldByWeight",
      "Unidad de Peso": "weightDetail.weightUnit",
      "Contenido Neto": "netContent",
      "Tamaño": "size",
      "Nombre": "name",
      "Medición": "measurement",
      "Fin de Promoción": "promotions.end",
      "Promoción Activa": "promotions.isActive",
      "Descuento": "promotions.discount",
      "Inicio de Promoción": "promotions.start",
      "Imagen": "image",
      "Es Visible": "isVisible",
      "Orden": "order",
      "Pie de Página": "footer",
      "Tipo": "type",
      "Impuesto": "pricing.tax",
      "Precio de Lista": "pricing.listPrice",
      "Precio Promedio": "pricing.avgPrice",
      "Precio": "pricing.price",
      "Costo": "pricing.cost",
      "Precio Mínimo": "pricing.minPrice",
      "Stock": "stock",
      "Garantía Activa": "warranty.status",
      "Cantidad de Garantía": "warranty.quantity",
      "Unidad de Garantía": "warranty.unit",
      "Cantidad a Comprar": "amountToBuy",
      "Rastreo de Inventario": "trackInventory",
      "Código de Barras": "barcode"
    }
  };
  

