
//Todo **************Pages*************************************************

export { Orders } from './pages/OrderAndPurchase/Order/Orders'
export { Purchases } from './pages/OrderAndPurchase/Compra/Purchases'
export { AddPurchase } from './pages/OrderAndPurchase/CreatePurchase/CreatePurchase'
export { Home } from './pages/Home/Home'
export { Inventory } from './pages/Inventario/pages/ItemsManager/Inventario'
export { MultimediaManager } from './pages/Inventario/pages/MultimediaManager/MultimediaManager'
export { Login } from './pages/Login/Login'
export { NotFound } from './pages/NotFound/NotFound'
export { Registro } from './pages/Registro/Registro'
export { Sales } from './pages/Venta/Ventas'
export { SignUp } from './pages/SignUp/SignUp'
export { Welcome } from './pages/Welcome/Welcome'
export { Contact } from './pages/Contact.jsx'
export { Receipt } from './pages/checkout/Receipt'
export { AddCustomProductModal } from './component/modals/AddCustomProductModal/AddCustomProductModal'
export { SetCustomProduct } from './component/modals/CustomProduct/SetCustomProduct/SetCustomProduct'
export { Setting } from './pages/setting/Setting'
export { TaxReceiptSetting } from './pages/setting/subPage/TaxReceipts/TaxReceIptSetting'
export { CategoryAdmin } from './pages/Category/CategoryAdmin'
export { ProviderAdmin } from './pages/Contact/Provider/ProviderAdmin'
export { ClientAdmin } from './pages/Contact/Client/ClientAdmin'
export { UserAdmin } from './pages/setting/subPage/Users/UserAdmin'

//Todo ***********Components*************************************************
export { ControlSearchProduct } from './component/ControlSearchProduct/ControlSearchProduct'
export { SearchList } from './component/ControlSearchProduct/SearchList'
export { Cart } from './component/cart/Cart.jsx'
export { MultiDisplayControl } from './component/MultiDisplayControl/MultiDisplayControl'
export { RequireAuth } from './component/RequireAuth'
export { ClientControl } from './component/contact/ClientControl/ClienteControl'
// export { ProductModal } from './component/modals/Product/ProductModal'
export { AddClientModal } from './component/modals/AddClient/AddClientModal'
export { Modal } from './component/modals/Modal'
export { ModalManager } from './component/modals/ModalManager'

//Todo ******Templates**********************************************
export { StatusIndicatorDot } from './pages/OrderAndPurchase/Order/components/StatusIndicatorDot/StatusIndicatorDot'
export { Counter } from './templates/system/Counter/Counter'
export { FloatingMessage } from './templates/system/FloatingMessage/FloatingMessage'
export { MenuApp } from './templates/MenuApp/MenuApp'
export { MenuWebsite } from './templates/MenuWebsite/MenuWebsite'
export { MenuComponents } from './templates/MenuComponents/MenuComponents'
export { FormControl, FormGroup, FormSubGroup, FormItemGroup } from './templates/system/Form/Form'
export { Button } from './templates/system/Button/Button'
export { ExpandButton } from './templates/system/Button/ExpandButton'
export { ChevronDownButton } from './templates/system/Button/ChevronDownButton'
export { PurchaseButton } from './templates/system/Button/PurchaseButton'
export { PlusIconButton } from './templates/system/Button/PlusIconButton'
export { ButtonGroup } from './templates/system/Button/ButtonGroup'
export { DeleteButton } from './templates/system/Button/DeleteButton'
export { EditButton } from './templates/system/Button/EditButton'
export { CloseButton } from './templates/system/Button/CloseButton'
export { ArrowLeftButton, ArrowRightButton } from './templates/system/Button/ArrowButton'
export { AddClientButton } from './templates/system/Button/AddClientButton'
export { AddProductButton } from './templates/system/Button/AddProductButton'
export { CancelPurchaseBtn } from './templates/system/Button/CancelPurchaseBtn'
export { Select } from './templates/system/Select/Select.jsx'
export { Product } from './templates/system/Product/Product/Product'
export { Client } from './templates/system/client/Client'
export { Grid } from './templates/system/Grid/Grid'
export { WebName } from './templates/system/WebName/WebName'
export { Account } from './templates/Account/Account'
export { ErrorMessage } from './templates/ErrorMassage/ErrorMassage'


